spring.application.name=delivery
spring.jpa.hibernate.ddl-auto=update
#Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost/orders
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
