spring.application.name=order

server:
    port: 8080

spring.jpa.hibernate.ddl-auto=update
#Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost/orders
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
payment-service.base-url=http://localhost:8082/
#Spring Kafka
spring.kafka.consumer.group-id=order-service-group
spring.kafka.bootstrap-servers=localhost:9092
order-paid-topic: orders.event
